# Generated by Django 5.2.17 on 2026-08-26 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(verbose_name='entrada prevista')),
                ('data_saida', models.DateTimeField(verbose_name='saída prevista')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('HOSPEDADO', 'Hospedado'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('check_in_em', models.DateTimeField(blank=True, null=True, verbose_name='check-in em')),
                ('check_out_em', models.DateTimeField(blank=True, null=True, verbose_name='check-out em')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor total')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hospedes.hospede', verbose_name='hóspede')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ('-criado_em',),
            },
        ),
    ]
