# Generated by Django 5.2.17 on 2026-08-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='documento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'hóspede',
                'verbose_name_plural': 'hóspedes',
                'ordering': ('-criado_em',),
            },
        ),
    ]
